### PR TITLE
Add release workflows and update icons/titles to match product

### PR DESCRIPTION
**Pull request by drustanyjt**
## Workflows

- Added 'build-and-release' triggered when a version tag is pushed to the team repo and creates a **draft release**.
- Added 'build-and-prerelease' triggered whenever a PR is merged to master and creates a **pre-release** for testing.
- Updated deprecated actions in other workflows

## Icons/Titles

- Changed app icon to match product site.
- Changed app title, jar file and save file to use product name (ClinicMate or some variation).

### CODE REVIEW

**Comment by drustanyjt** [comment]
Closes #49

**Comment by drustanyjt** [comment]
Closes #45

**Review by tengcharmaine — APPROVED** [review]
LGTM

**Review by jiahui0309 — APPROVED** [review]
LGTM!

**Pull request merged**
