### PR TITLE
Edit Developer Guide Design section

### LINKED ISSUE #226: Update design section + look through documentation, logging .... section

### PR DESCRIPTION
**Pull request by jiahui0309**
Closes #226 

Screenshot 2024-04-13 at 4 42 12 PM
Screenshot 2024-04-13 at 4 43 47 PM
Screenshot 2024-04-13 at 4 44 19 PM
Screenshot 2024-04-13 at 9 51 02 PM
Screenshot 2024-04-13 at 11 02 47 PM

### CODE REVIEW

**Comment by drustanyjt** [comment]
@jiahui0309 sorry abit hard to see without screenshot. Do you think you can add for the diagram you changed?

**Comment by jiahui0309** [comment]
@drustanyjt done!

**Comment by drustanyjt** [comment]
image
@jiahui0309 note doesn't seem to work like this in the UI

**Comment by drustanyjt** [comment]
@jiahui0309 AddressBook.java on line 104 has a method that returns Note. Should AddressBook have its own dependency arrow as well? Otherwise LGTM

**Review by drustanyjt — APPROVED** [review]
LGMT

**Pull request merged**
