### PR TITLE
Edit UI features of ClinicMate

### LINKED ISSUE #98: UI changes
- [x] Change background colour - white
- [x] Rounded edges for each Person entry
- [x] Gender and age move to beside name
- [x] Gender make it coloured [same as tags]
- [x] Add labels for the fields
- [x] Increase font size

### PR DESCRIPTION
**Pull request by jiahui0309**
Changed UI features as discussed. (Closes https://github.com/AY2324S2-CS2103T-F14-2/tp/issues/98). This PR covers:
1.  Changing to white background
2.  Having rounded edges for each Person entry
3.  Changing the position of gender and age field
4.  Adding labels for each Person fields 
5.  Increasing overall font size
6. The program can compile and run without a problem.

The UI currently looks like this:
Screenshot 2024-03-23 at 9 24 02 PM
Screenshot 2024-03-23 at 9 24 20 PM

### CODE REVIEW

**Review by tengcharmaine — APPROVED** [review]
LGTM! Maybe can consider whether the help box want change to light mode also? If yall think its okay then I am okay!

**Review by Jayne1010 — CHANGES_REQUESTED** [review]
Is it possible to make the comment box just slightly bigger? For the success and error message

**Comment by jiahui0309** [comment]
@Jayne1010 It looks like this now! Do let me know if further size changes are needed
Screenshot 2024-03-24 at 11 45 51 AM

**Review by Jayne1010 — APPROVED** [review]
LGTM

**Pull request merged**
